# 1 Lesson

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
print(np.__version__)

2.1.2


In [4]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


# 2 Lesson

In [5]:
import numpy as np

In [6]:
x=np.array((1,2,3,4))

 This is tuple

In [8]:
print(x)

[1 2 3 4]


2 Dimensional array

In [11]:
x=np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
print(x)

[[1 2 3 4]
 [5 6 7 8]]


Get the dimension of the array

In [13]:
print(x.ndim)

2


Convert to the dimension we want

In [14]:
x=np.array([1,2,3,4],ndmin=4)

In [15]:
print(x)

[[[[1 2 3 4]]]]


Indexing

In [16]:
x=np.array([1,2,3,4])

In [17]:
print(x[2])

3


In [18]:
print(x[2]+x[3])

7


In [21]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
print(x[1,0])

4


In [23]:
x=np.array([[[1,2],[3,4],[5,6]]])

In [24]:
print(x[0,0,0])

1


Slicing

In [25]:
x=np.array([1,2,3,4,5,6])

In [26]:
print(x[1:4])

[2 3 4]


In [28]:
print(x[-4:])

[3 4 5 6]


In [30]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
print(x[1,1:])

[5 6]


In [32]:
print(x[:,2])

[3 6 9]


In [33]:
print(x.dtype)

int64


In [34]:
x=np.array(['python','java','c++'])

In [35]:
print(x.dtype)

<U6


In [36]:
x=np.array([1,2,3,4],dtype='f')

In [37]:
print(x.dtype)

float32


In [39]:
x=np.array([1,2,3,4],dtype='U')
print(x)

['1' '2' '3' '4']


In [40]:
x=np.array([1,2,3,4])
for i in x:
    print(i)

1
2
3
4


In [42]:
x=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6


In [43]:
for i,j in np.ndenumerate(x):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [45]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x.shape)

(2, 4)


In [46]:
x=np.array([1,2,3,4],ndmin=5)
print(x)
print(x.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [47]:
x=np.array([1,2,3,4,5,6,7,8,9])
new=x.reshape(3,3)
print(new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
new=x.reshape(1,9)
print(new)

[[1 2 3 4 5 6 7 8 9]]


In [52]:
x=np.array([[1,2,3],[4,5,6]])
new = x.reshape(-1)
print(new)

[1 2 3 4 5 6]


In [55]:
arr=np.array([1,2,3,4,5,6,7])
x=np.where(arr==4)
print(x)

(array([3]),)


In [56]:
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5]),)


In [61]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr = np.concatenate((arr1, arr2))  
print(newarr)

[1 2 3 4 5 6 7 8]


In [64]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
newarr = np.concatenate((arr1, arr2) , axis=1)  
print(newarr)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [65]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
newarr = np.concatenate((arr1, arr2) , axis=0)  
print(newarr)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [69]:
x=np.array([1,2,3,4,5,6])
newarr=np.array_split(x,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
